[[redirects]]
  from = "/api/*"
  to = "https://frontend-take-home-service.fetch.com/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Credentials = "true" }
